version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - even-network
  notebook:
    image: jupyter/pyspark-notebook:latest
    restart: always
    container_name: notebook
    ports:
      - 8888:8888
    environment:
       JUPYTER_TOKEN: password
    volumes:
      - ./postgresql-42.3.5.jar:/usr/local/spark/jars/postgresql-42.3.5.jar
      - ./clicks.parquet.gzip:/home/jovyan/clicks.parquet.gzip
      - ./leads.parquet.gzip:/home/jovyan/leads.parquet.gzip
      - ./rate_tables.parquet.gzip:/home/jovyan/rate_tables.parquet.gzip
      - ./EvenAnalyticsNotebook.ipynb:/home/jovyan/EvenAnalyticsNotebook.ipynb
    networks:
      - even-network
networks:
  even-network:
    driver: bridge